# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "ZetaCode"
email: "bsh0236@gmail.com"
description: "An engineer's programming stories"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zetacode.com"
twitter_username: jekyllrb
github_username:  bavernet

# Build settings
markdown: kramdown

# Site Owner configuration
owner:
  name: Baver
  avatar: baver.jpg
  job: "Research & System Engineer"
  bio: "Enjoy programming life"
  email: bsh0236@gmail.com
  comments: true
  disqus-shortname: zetacode
  twitter:
  facebook:
  google:
    plus:
    analytics: 'UA-76755767-1'
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
